name: Portfolio Build & Deploy

on:
push:
branches: 
-dev

env:
CI: false

jobs:
build:
name: Build
runs-on: ubuntu-latest

steps:
-name: Checkout repo
uses: actions/checkout@v2

-name: Setup Node
uses: actions/setup-node@v1
with: 
node-version: 22

-name: Install dependencies
uses: npm install

-name: Build project
run: npm run build

-name: Upload production-ready build files
uses: actions/upload-artifact@v2
with: 
name: production-files
path: ./build

deploy:
name: Deploy
needs: build
run-on: ubuntu-latest
if: github.ref =='refs/heads/dev'

steps:
-name: Download artifact
uses: actions/download-artifact@v2
with: 
name: production-files
path: ./build

-name: Deploy to Github pages
uses: peaceiris/actions-gh-pages@v3
with:
github_tolen: #{{ secret.TOKEN }}
publish_dir: ./build
